// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaE5Z_kpoqUn-AsOWGMDLyig9Tj9UKfVA',
    appId: '1:226521509239:web:4db0977a07cbf812a20572',
    messagingSenderId: '226521509239',
    projectId: 'shoes-store-f3c9e',
    authDomain: 'shoes-store-f3c9e.firebaseapp.com',
    storageBucket: 'shoes-store-f3c9e.appspot.com',
    measurementId: 'G-Z5WNVG8Z7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBssjl11OEqy6xoL1W6kGndn9ZP1QQefIE',
    appId: '1:226521509239:android:b463fa7bc059f8b2a20572',
    messagingSenderId: '226521509239',
    projectId: 'shoes-store-f3c9e',
    storageBucket: 'shoes-store-f3c9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-r2y-IQx0-o5EGzlSmLpzy1SkNb5UvBE',
    appId: '1:226521509239:ios:c3027d854482f66aa20572',
    messagingSenderId: '226521509239',
    projectId: 'shoes-store-f3c9e',
    storageBucket: 'shoes-store-f3c9e.appspot.com',
    iosBundleId: 'com.example.shoesStore',
  );
}
